### ISSUE TITLE
Library specific to Node.js?

### ISSUE THREAD

**Issue by SoftCircuits** [ben-ng/convert-units#53]
After doing some research, it seems that the `require()` syntax used throughout this library is specific to Node.js.

I don't understand why a library like this can't be written for "bare bones" JavaScript. That would make it useful to the widest range of users. Instead, people like me (who have extensive programming experience, but not much with JavaScript) are kind of left out of the party.

Just sayin'

**Comment by ben-ng** [comment]
This library isn't one giant file because it would be more difficult to maintain and contribute to.

That said, you can use always something like [browserify](https://github.com/substack/node-browserify#usage) to create a standalone version of this module:

```sh
browserify convert-units/index.js --standalone -o convert-units-dist.js
```

I'll accept a pull request that makes this library easier to consume without sacrificing CommonJS compatibility or maintainability.
